name: Auto Deploy hugo
on:
  push:
    branches:
      - main 
  workflow_run:
    workflows: ["Generate GitBlog README"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: wjianbo/wjianbo.github.io
        DEPLOY_BRANCH: master
        DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Tokyo