name: blogger

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - main 
    paths:
      - blogger/target/

env:
  GITHUB_NAME: wjianbo 
  GITHUB_EMAIL: jnb.wang@gmail.com

jobs:
  sync:
    name: Run blogger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run blogger
        run: |
          blogger/target/debug/blogger
          ls